### ISSUE TITLE
Limitations in the way blang loads models implemented directly in Java

### ISSUE THREAD

**Issue by alexandrebouchard** [UBC-Stat-ML/blangDSL#54]
- Syntax is different, `new QualifiedName` instead of `QualifiedName`
- Factor must be in an imported jar; problems with loading one in the current project

**Comment by cubranic** [comment]
Also, I have to fully qualify the name, even when it's imported by the model. (Likely because it's inspecting it from `SingleBlangModelInferrer` with "Class.forName" (method `constructorParameters`), which won't be aware of imports in the model.

**Comment by cubranic** [comment]
Commit ef5b5e7a8aa6a03f58d2b924bf25fdfab06e48e1 fixes at least the latter issue: we can again use the short name of a Java distribution, if it's included in the model's `import`s.

The key was using `JvmTypeReference` for it in the grammar, instead of `QualifiedName`, because that one plays nicely with the imports and the rest of the Java model mechanisms in XBase.

**Comment by alexandrebouchard** [comment]
Yeah more fundamental: the class loader probably has access to nothing else than DSL classes. Consider removing that feature, instead consider solution as in branch ``special-behaviour-for-empty-laws``

**Comment by alexandrebouchard** [comment]
Does not seem to be an issue in practice
